FROM golang:1.17.4

COPY ./backend /app/backend
COPY ./test-data-manager /app/test-data-manager

WORKDIR /app/test-data-manager

ARG GO_BUILD_TAGS="dev"
RUN go build --tags "$GO_BUILD_TAGS" -o /app/main .

ENTRYPOINT ["/app/main"]
