FROM golang:1.16.7-alpine

COPY ./backend /app/backend
COPY ./test-data-manager /app/test-data-manager

WORKDIR /app

ARG GO_BUILD_TAGS="dev"
RUN cd test-data-manager && \
    go build --tags "$GO_BUILD_TAGS" -o /app/main .

ENTRYPOINT ["/app/main"]
