runtime: go116
instance_class: B8
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
# Circle CI generates the env_variables.yaml file during deployment.
includes:
  - env_variables.yaml
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
