version: '3.2'
services:
  whatgotdone:
    build:
      context: ../
      args:
        NPM_BUILD_MODE: staging
        GO_BUILD_TAGS: staging
    environment:
      - PORT=3123
      - CSRF_SECRET_SEED=dummy-staging-seed
      - GOOGLE_CLOUD_PROJECT=whatgotdone-staging
    env_file:
      - staging-secrets.env
    volumes:
      - ../service-account-creds-staging.json:/app/service-account-creds-staging.json
      - ./:/app/e2e
  cypress:
    image: "cypress/included:3.4.0"
    depends_on:
      - whatgotdone
    environment:
      - CYPRESS_baseUrl=http://whatgotdone:3123
      - DEBUG=cypress:server:request,cypress:server:server,cypress:server:proxy,cypress:network:agent,cypress:server:browsers
      # Set test timezone to Los Angeles so that we're more likely to catch
      # incorrect UTC vs. local date translations.
      - TZ=America/Los_Angeles
    working_dir: /e2e
    volumes:
      - ./:/e2e
