#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

./dev-scripts/run-go-tests
./dev-scripts/check-go-formatting
./dev-scripts/build-backend dev
./dev-scripts/build-backend staging
./dev-scripts/build-backend prod

cd frontend
NODE_ENV="production" npm run lint
