#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

./dev-scripts/run-go-tests
./dev-scripts/check-go-formatting

pushd backend
go build -o /dev/null --tags 'dev' main.go
go build -o /dev/null --tags 'staging' main.go
go build -o /dev/null main.go
popd

cd frontend
NODE_ENV="production" npm run lint
