#!/bin/bash

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Echo commands
set -x

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

cd frontend
npm install
npm run build -- --mode development
