#!/bin/bash

# Exit on first failing command.
set -e

# Echo commands
set -x

if [[ -z $1 ]]; then
  MODE="prod"
else
  MODE="$1"
fi
readonly MODE

# Exit on unset variable.
set -u

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

cd frontend
npm install
npm run build -- --mode "${MODE}"
