#!/bin/bash

set -eux

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

TIMESTAMP=$(date --iso-8601=minutes | sed 's/://g' | sed 's/+0000/Z/g')

# We need to export this so it's available to litestream.
export DB_PATH="data/store.db"

readonly DB_COPY_PATH="data/${TIMESTAMP}.db"

# Delete .db, .db-shm, and .db-wal files if they exist.
if compgen -G "${DB_PATH}*" > /dev/null; then
  rm ${DB_PATH}*
fi

# Load production credentials.
set +x
# shellcheck disable=SC1091
. .env.prod
set -x

export LITESTREAM_ENDPOINT
export LITESTREAM_ACCESS_KEY_ID
export LITESTREAM_SECRET_ACCESS_KEY
export LITESTREAM_BUCKET

# Retrieve production DB.
litestream restore -v -config litestream.yml -o "${DB_COPY_PATH}" "${DB_PATH}"
cp "${DB_COPY_PATH}" "${DB_PATH}"
