#!/usr/bin/env bash

# Migrate avatars from GCS to SQLite.

set -eux

pushd "$(mktemp --directory)"

gsutil -m cp gs://media.whatgotdone.com/avatars/*/*-avatar-300px.jpg ./

for filename in *.jpg; do
  echo "$filename"
  parts=(${filename//-/ })
  USERNAME="${parts[0]}"
  HEX="$(xxd -p $filename | tr -d '\n')"
  sqlite3 /home/mike/whatgotdone/data/store.db "UPDATE user_profiles SET avatar = X'$HEX', avatar_width=300 WHERE username='${USERNAME}'"
done
