#!/usr/bin/env bash

# Migrate avatars from GCS to SQLite.

set -eux

pushd "$(mktemp --directory)"

gsutil -m cp gs://media.whatgotdone.com/avatars/*/*-avatar-300px.jpg ./

for filename in *.jpg; do
  echo "$filename"
  parts=(${filename//-/ })
  USERNAME="${parts[0]}"
  HEX="$(xxd -p $filename | tr -d '\n')"
  sqlite3 /home/mike/whatgotdone/data/store.db "INSERT INTO avatars (username, avatar, width, last_modified) VALUES ('${USERNAME}', X'$HEX', 300, strftime('%Y-%m-%d %H:%M:%SZ', 'now', 'utc'))"
done
