#!/bin/bash

# Check for trailing whitespace

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Echo commands
set -x

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

. dev.env

readonly BUILD_DIR="$(mktemp -d)"

pushd test-data-manager
go build --tags "dev" -o "${BUILD_DIR}" .
popd

"${BUILD_DIR}/test-data-manager" -source "test-data-manager/dev-data.yaml"
