#!/bin/bash

# Check for trailing whitespace

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Echo commands
set -x

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."


# Wipe the existing database (.db, .db-shm, and .db-wal files).
readonly DB_FILES_PATTERN="data/store.db*"
if compgen -G "${DB_FILES_PATTERN}" > /dev/null; then
  rm ${DB_FILES_PATTERN}
fi

. dev.env

pushd test-data-manager
go build --tags "dev" -o bin/test-data-manager .
popd

test-data-manager/bin/test-data-manager -source "test-data-manager/dev-data.yaml"
