#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

cd test-data-manager

export GOOGLE_CLOUD_PROJECT="dummy-local-gcp-project"
export FIRESTORE_EMULATOR_HOST="localhost:8080"
go build --tags 'dev' -o /tmp/test-data-manager . && \
  /tmp/test-data-manager -source "dev-data.yaml"
