#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

if [ "$1" = "--quick" ]; then
  quick_test=""
  flags=""
else
  quick_test="1"
  flags="-race --coverprofile=.coverage.out"
fi

# Exit on unset variable.
set -u

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

# Install staticcheck if it's not present.
STATICCHECK_PATH="$(go env GOPATH)/bin/staticcheck"
if [ ! -f "${STATICCHECK_PATH}" ]; then
    go install honnef.co/go/tools/cmd/staticcheck@latest
fi

pushd backend
go test -v $flags ./...
go vet ./...
$STATICCHECK_PATH ./...

if [ ! -z "$quick_test" ]; then
  go tool cover -html .coverage.out -o .coverage.html
fi
popd

pushd test-data-manager
go vet -tags dev ./...
$STATICCHECK_PATH ./...
popd
