#!/bin/bash

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

REBUILD_BIN="1"
if [[ "$1" = "--skip-rebuild" ]]; then
  REBUILD_BIN=""
fi
readonly REBUILD_BIN

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

if [[ -n "${REBUILD_BIN}" ]]; then
  ./dev-scripts/build-backend staging
fi

# Load dev environment vars.
set +x
# shellcheck disable=SC1091
. dev.env
set -x

npx playwright test
