#!/bin/bash

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

if [ "$1" = "--skip-build" ]; then
  flags=""
else
  flags="--build"
fi

cd integration
npm install
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
  docker-compose up --exit-code-from cypress --abort-on-container-exit $flags
