#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

go test -v -coverprofile=.coverage.out ./...
go vet ./...
go tool cover -html .coverage.out -o .coverage.html
