#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

if [ "$1" = "--quick" ]; then
  quick_test=""
  flags=""
else
  quick_test="1"
  flags="-race --coverprofile=.coverage.out"
fi

# Exit on unset variable.
set -u

pushd backend
go test -v $flags ./...
go vet ./...

if [ ! -z "$quick_test" ]; then
  go tool cover -html .coverage.out -o .coverage.html
fi
popd

pushd test-data-manager
go vet -tags dev ./...
popd
