#!/usr/bin/env bash

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Echo commands
set -x

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

SCREEN_SESSION_NAME="whatgotdone-frontend"

# Kill any previous frontend hot reloading screen session.
screen -X -S "${SCREEN_SESSION_NAME}" quit || true

# Run the hot reloading frontend server in a background screen session.
screen -Sdm "${SCREEN_SESSION_NAME}" ./dev-scripts/serve-frontend

./dev-scripts/serve-backend
