#!/bin/bash

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Echo commands
set -x

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

. env.dev
if [[ -f .env.dev.local ]]; then
    . .env.dev.local
fi

# Install modd if it's not present.
MODD_PATH="$(go env GOPATH)/bin/modd"
readonly MODD_PATH
readonly MODD_VERSION="v0.0.0-20211215124449-6083f9d1c171"
if [[ ! -f "${MODD_PATH}" ]]; then
    go install \
      -ldflags=-linkmode=external \
      "github.com/cortesi/modd/cmd/modd@${MODD_VERSION}"
fi

# Run modd for hot reloading.
$MODD_PATH
