#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

. dev.env

readonly CONTAINER_NAME="firestore-emulator"

docker rm -f "${CONTAINER_NAME}"
docker run \
  --detach \
  --env "FIRESTORE_PROJECT_ID=${GOOGLE_CLOUD_PROJECT}" \
  --env "PORT=8080" \
  --publish 8080:8080 \
  --name "${CONTAINER_NAME}" \
  mtlynch/firestore-emulator
