#!/usr/bin/env bash

set -ex

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

export DB_PATH="$1"

set -u

set +x
. .env.prod
set -x

if [[ -z "${DB_PATH}" ]]; then
      echo "usage: upload-prod-db [db_path]" && exit 1
fi

read -p "Really overwrite prod database? (y/N): " choice

echo "Choice is ${choice}"

if [[ $choice != "y" ]]; then
  echo "Upload aborted"
  exit 1
fi

flyctl scale count 0 --yes

echo "Replacing prod database"

litestream replicate -config litestream.yml -exec "sleep 30"

flyctl scale count 1 --yes
